pstore: fix of errors in the code by oneplus
baf_lock has been converted to semaphore.(f72ecfe93a80a1e83bc9b13f2c66c8af3fb456d8)

../../../../../../kernel/oneplus/sm8150/fs/pstore/platform.c:637:35:
error: incompatible pointer types passing 'struct semaphore *' to
parameter of type 'spinlock_t *' (aka 'struct spinlock *')
[-Werror,-Wincompatible-pointer-types]
        if (!spin_trylock_irqsave(&psinfo->buf_lock, flags))
                                  ^~~~~~~~~~~~~~~~~
../../../../../../kernel/oneplus/sm8150/include/linux/spinlock.h:387:42:
note: expanded from macro 'spin_trylock_irqsave'
        raw_spin_trylock_irqsave(spinlock_check(lock), flags); \
                                                ^~~~
../../../../../../kernel/oneplus/sm8150/include/linux/spinlock.h:278:19:
note: expanded from macro 'raw_spin_trylock_irqsave'
        raw_spin_trylock(lock) ? \
                         ^~~~
../../../../../../kernel/oneplus/sm8150/include/linux/spinlock.h:194:68:
note: expanded from macro 'raw_spin_trylock'
_raw_spin_trylock(lock))
                                                                    ^~~~
../../../../../../kernel/oneplus/sm8150/include/linux/compiler_types.h:44:28:
note: expanded from macro '__cond_lock'
                           ^
../../../../../../kernel/oneplus/sm8150/include/linux/spinlock.h:304:67:
note: passing argument to parameter 'lock' here
static __always_inline raw_spinlock_t *spinlock_check(spinlock_t *lock)
                                                                  ^
../../../../../../kernel/oneplus/sm8150/fs/pstore/platform.c:640:27:
error: incompatible pointer types passing 'struct semaphore *' to
parameter of type 'spinlock_t *' (aka 'struct spinlock *')
[-Werror,-Wincompatible-pointer-types]
        spin_lock_irqsave(&psinfo->buf_lock, flags);
                          ^~~~~~~~~~~~~~~~~
../../../../../../kernel/oneplus/sm8150/include/linux/spinlock.h:347:39:
note: expanded from macro 'spin_lock_irqsave'
        raw_spin_lock_irqsave(spinlock_check(lock), flags);     \
                                             ^~~~
../../../../../../kernel/oneplus/sm8150/include/linux/spinlock.h:223:34:
note: expanded from macro 'raw_spin_lock_irqsave'
                flags = _raw_spin_lock_irqsave(lock);   \
                                               ^~~~
../../../../../../kernel/oneplus/sm8150/include/linux/spinlock.h:304:67:
note: passing argument to parameter 'lock' here
static __always_inline raw_spinlock_t *spinlock_check(spinlock_t *lock)
                                                                  ^
../../../../../../kernel/oneplus/sm8150/fs/pstore/platform.c:645:28:
error: incompatible pointer types passing 'struct semaphore *' to
parameter of type 'spinlock_t *' (aka 'struct spinlock *')
[-Werror,-Wincompatible-pointer-types]
    spin_unlock_irqrestore(&psinfo->buf_lock, flags);
                           ^~~~~~~~~~~~~~~~~
../../../../../../kernel/oneplus/sm8150/include/linux/spinlock.h:370:64:
note: passing argument to parameter 'lock' here
static __always_inline void spin_unlock_irqrestore(spinlock_t *lock,
unsigned long flags)
                                                               ^
3 errors generated.

Signed-off-by: tumayouzi <tumayouzi@gmail.com>